version: "3"
services:
  postgres:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/posgresql/data

  test-db:
    container_name: test_db
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - test_db_vol:/var/lib/posgresql/data

  back:
    container_name: back
    image: node:lts-alpine
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5555:5555"
    command: sh -c "npm i -g @nestjs/cli; npm install; npx prisma generate && npx prisma migrate reset ; npx prisma migrate dev --name build; npx prisma db seed; npm run start:dev;"
    volumes:
      - "./backend:/back"
    working_dir: /back

  frontend:
    container_name: front
    image: node:lts-alpine
    restart: unless-stopped
    ports:
      - "4200:4200"
    command: sh -c "apk add bash && npm install && npm run dev"
    volumes:
      - "./frontend:/front"
    working_dir: /front

volumes:
  postgres:
  test_db_vol:
